name: cmake

on: [push, pull_request]

env:
  SYSTEMC_ROOT_HOME: "${{github.workspace}}/systemc"
  RAPIDJSON_HOME: "${{github.workspace}}/rapidjson"
  CCI_ROOT_HOME: ${{github.workspace}}/build

jobs:
  build:
    name: "Build"
    strategy:
      fail-fast: false
      matrix:
        systemc_version: [2.3.2, 2.3.3, 2.3.4]
        os:
          - name: ubuntu
            version: 20.04
            cxx_compiler: g++-9
            c_compiler: gcc-9
          - name: ubuntu
            version: 20.04
            cxx_compiler: clang++-9
            c_compiler: clang-9
            deps: 'clang-9'
          - name: ubuntu
            version: 22.04
            cxx_compiler: g++-11
            c_compiler: gcc-11
          - name: ubuntu
            version: 22.04
            cxx_compiler: clang++-11
            c_compiler: clang-11
            deps: 'clang-11'
    runs-on: ${{matrix.os.name}}-${{matrix.os.version}}

    steps:
    - name: Setup environment vars
      run: |
        echo "SYSTEMC_HOME=${SYSTEMC_ROOT_HOME}/${{matrix.systemc_version}}" >> ${GITHUB_ENV}
        echo "CCI_HOME=${CCI_ROOT_HOME}/release-sc_${{matrix.systemc_version}}" >> ${GITHUB_ENV}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Dependencies Ubuntu
      if: matrix.os.name == 'ubuntu'
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y \
          rapidjson-dev \
          ${{matrix.os.deps}}

    - name: Cache SystemC ${{matrix.systemc_version}} (${{matrix.os.cxx_compiler}})
      id: cache-SystemC
      uses: actions/cache@v3
      with:
        path: ${{env.SYSTEMC_HOME}}
        key: ${{matrix.os.name}}-${{matrix.os.version}}-cmake-systemc-${{matrix.systemc_version}}-${{matrix.os.cxx_compiler}}

    - name: Setup SystemC
      if: steps.cache-SystemC.outputs.cache-hit != 'true'
      env:
        SYSTEMC_URL: "https://github.com/accellera-official/systemc/archive/refs/tags"
      run: |
        mkdir -p ${SYSTEMC_HOME}
        mkdir -p ${{github.workspace}}/tmp/systemc-${{matrix.systemc_version}} && cd ${{github.workspace}}/tmp/systemc-${{matrix.systemc_version}}
        wget ${SYSTEMC_URL}/${{matrix.systemc_version}}.tar.gz
        tar -xvf ${{matrix.systemc_version}}.tar.gz
        cd systemc-${{matrix.systemc_version}}
        mkdir build && cd build
        cmake  \
          -DCMAKE_CXX_COMPILER=${{matrix.os.cxx_compiler}} \
          -DCMAKE_C_COMPILER=${{matrix.os.c_compiler}} \
          -DCMAKE_CXX_STANDARD=11 \
          -DCMAKE_INSTALL_PREFIX=${SYSTEMC_HOME} \
          -DCMAKE_BUILD_TYPE=Release \
          ..
        make -j`nproc`
        make install

    - name: Configure
      run: |
        mkdir -p ${CCI_HOME}/build && cd ${CCI_HOME}/build
        cmake \
          -DCMAKE_CXX_COMPILER=${{matrix.os.cxx_compiler}} \
          -DCMAKE_C_COMPILER=${{matrix.os.c_compiler}} \
          -DCMAKE_CXX_STANDARD=11 \
          -DCMAKE_PREFIX_PATH=${SYSTEMC_HOME}/lib/cmake/SystemCLanguage \
          -DCMAKE_INSTALL_PREFIX=${CCI_HOME} \
          -DCMAKE_BUILD_TYPE=Release \
          ../../..

    - name: Build
      run: |
        cd ${CCI_HOME}/build
        make -j `nproc`
        make install

    - name: Test
      run: |
       cd ${CCI_HOME}/build
       make check
